# Path to your oh-my-zsh installation.
ZSH=/usr/share/oh-my-zsh/
BASEDIR="$HOME/dotfiles/zsh"
ZSH_CUSTOM="$BASEDIR/custom"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="gnzh"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git tmuxinator)

source $ZSH/oh-my-zsh.sh

source "$BASEDIR/functions"
source "$BASEDIR/env"

eval "$(rbenv init -)"

# vi mode
bindkey -v
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward
bindkey '^k' history-beginning-search-backward
bindkey '^j' history-beginning-search-forward
bindkey '^q' push-line

export KEYTIMEOUT=1

eval "$(fasd --init posix-alias zsh-hook zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install)"
alias v='f -e vim'
alias m='f -e mpv'
alias o='a -e xdg-open'
alias j='fasd_cd -d'

_GREP_OPTIONS=$GREP_OPTIONS
alias grep="grep $_GREP_OPTIONS"
unset GREP_OPTIONS

#task calendar
#khal agenda
#task rc.context=none next
